In [1]:
from derivative_cnn import derivative_layer_input_convolution_multiple_point
import numpy as np

In [2]:
list_P: list[np.ndarray] = np.random.randint(1, 3, (5, 3, 3, 4))

K_11 = np.random.randint(1, 3, (2, 2, 4))
K_12 = np.random.randint(1, 3, (2, 2, 4))
K_13 = np.random.randint(1, 3, (2, 2, 4))
K_14 = np.random.randint(1, 3, (2, 2, 4))

list_Filter: list[np.ndarray] = [K_11, K_12, K_13, K_14]
list_dL_dZk: list[np.ndarray] = np.random.randint(1, 3, (5, 2, 2, 4))
stride_default: int=1

In [ ]:
result = derivative_layer_input_convolution_multiple_point(
    list_P, 
    list_Filter,
    list_dL_dZk,
    stride_default
)

In [4]:
result.shape

(5, 3, 3, 4)

In [27]:
result[2][:,:,1]

array([[ 9., 17.,  7.],
       [21., 36., 16.],
       [11., 18., 10.]])

In [28]:
K_11[:,:,1]


array([[2, 2],
       [1, 2]])

In [29]:
K_12[:,:,1]


array([[2, 2],
       [2, 1]])

In [30]:
K_13[:,:,1]


array([[1, 2],
       [2, 1]])

In [31]:
K_14[:,:,1]

array([[1, 1],
       [1, 2]])

In [32]:
list_dL_dZk[2][:, :, 0]


array([[1, 1],
       [2, 2]])

In [33]:
list_dL_dZk[2][:, :, 1]


array([[2, 1],
       [2, 1]])

In [34]:
list_dL_dZk[2][:, :, 2]


array([[2, 1],
       [2, 1]])

In [35]:
list_dL_dZk[2][:, :, 3]

array([[1, 1],
       [1, 2]])