In [1]:
import numpy as np

In [2]:
o = np.array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [1., 1., 4., 1.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [2., 1., 4., 2.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [2., 2., 4., 1.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [2., 1., 2., 1.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [2., 2., 4., 2.]]]])

In [3]:
o.shape

(5, 2, 2, 4)

In [4]:
o[0]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [1., 1., 4., 1.]]])

In [7]:
np.sum(o, axis=(1, 2, 3), keepdims=True).shape

(5, 1, 1, 1)

In [6]:
np.sort(np.unique([1, 2, 3, 3]))

array([1, 2, 3])

In [32]:
list_P_2 = np.random.randint(0, 2, (3, 3, 3, 4))

In [33]:
print(list_P_2[0][:, :, 0])
print(list_P_2[0][:, :, 1])
print(list_P_2[0][:, :, 2])
print(list_P_2[0][:, :, 3])

[[0 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [1 1 0]]
[[0 1 0]
 [1 1 1]
 [0 0 0]]
[[0 0 1]
 [1 0 1]
 [0 0 1]]


In [34]:
print(list_P_2[1][:, :, 0])
print(list_P_2[1][:, :, 1])
print(list_P_2[1][:, :, 2])
print(list_P_2[1][:, :, 3])

[[1 0 0]
 [1 1 0]
 [1 0 0]]
[[0 1 0]
 [0 0 0]
 [1 0 0]]
[[0 1 0]
 [1 1 1]
 [1 1 0]]
[[1 1 1]
 [0 1 1]
 [1 1 1]]


In [35]:
print(list_P_2[2][:, :, 0])
print(list_P_2[2][:, :, 1])
print(list_P_2[2][:, :, 2])
print(list_P_2[2][:, :, 3])

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 0]
 [0 1 0]]
[[1 1 1]
 [1 1 0]
 [1 1 0]]
[[0 1 1]
 [0 0 1]
 [1 1 1]]


In [36]:
list_P_2.flatten(order="C")

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1])

In [37]:
A_0 = list_P_2.flatten(order="C").reshape((36, 3), order="F")

In [38]:
A_0

array([[0, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       [1, 0, 0],
       [1, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 0],
       [1, 0, 1],
       [0, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [39]:
result = A_0.T.reshape((3, 3, 3, 4), order="C")

In [40]:
print(result[0][:, :, 0])
print(result[0][:, :, 1])
print(result[0][:, :, 2])
print(result[0][:, :, 3])

[[0 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [1 1 0]]
[[0 1 0]
 [1 1 1]
 [0 0 0]]
[[0 0 1]
 [1 0 1]
 [0 0 1]]


In [41]:
print(result[1][:, :, 0])
print(result[1][:, :, 1])
print(result[1][:, :, 2])
print(result[1][:, :, 3])

[[1 0 0]
 [1 1 0]
 [1 0 0]]
[[0 1 0]
 [0 0 0]
 [1 0 0]]
[[0 1 0]
 [1 1 1]
 [1 1 0]]
[[1 1 1]
 [0 1 1]
 [1 1 1]]


In [42]:
print(result[2][:, :, 0])
print(result[2][:, :, 1])
print(result[2][:, :, 2])
print(result[2][:, :, 3])

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 0]
 [0 1 0]]
[[1 1 1]
 [1 1 0]
 [1 1 0]]
[[0 1 1]
 [0 0 1]
 [1 1 1]]
