In [1]:
import sys
sys.path.append(r"D:\code\selenium\data_analytics\try_cnn")

In [2]:
import numpy as np
from utils_cnn import convolution_multiple_kernel_multiple_point

In [6]:
list_X = np.random.randint(0, 2, (5, 3, 3, 2))

In [7]:
K_11 = np.random.randint(0, 2, (2, 2, 2))
K_12 = np.random.randint(0, 2, (2, 2, 2))

In [8]:
bias_11 = 2
bias_12 = 3

In [23]:
result = convolution_multiple_kernel_multiple_point(list_X, [K_11, K_12], [bias_11, bias_12])

In [24]:
result.shape

(5, 2, 2, 2)

In [25]:
K_11[:,:,0]

array([[0, 1],
       [1, 1]])

In [26]:
K_11[:,:,1]

array([[1, 1],
       [0, 1]])

In [27]:
K_12[:,:,0]

array([[0, 0],
       [0, 1]])

In [28]:
K_12[:,:,1]

array([[1, 1],
       [0, 0]])

In [33]:
list_X[2][:,:,0]

array([[1, 0, 0],
       [1, 1, 0],
       [0, 0, 1]])

In [34]:
list_X[2][:,:,1]

array([[1, 1, 1],
       [1, 1, 0],
       [0, 0, 1]])

In [35]:
result[2][:,:,0]

array([[7., 5.],
       [5., 5.]])

In [36]:
result[2][:,:,1]

array([[6., 5.],
       [5., 5.]])