In [1]:
import pandas as pd
import numpy as np

np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
import keras.layers as layers
import keras

Lệnh np.set_printoptions(precision=3, suppress=True) trong numpy được dùng để tùy chỉnh cách hiển thị các mảng numpy trên màn hình. Cụ thể:

- precision=3: Xác định số lượng chữ số thập phân hiển thị cho các số dấu phẩy động (floating-point). Ở đây, precision=3 có nghĩa là chỉ hiển thị 3 chữ số thập phân.

- suppress=True: Chỉ định việc không hiển thị số mũ khoa học đối với các số rất nhỏ. Nếu suppress=True, những số rất nhỏ (nhưng không phải là 0) sẽ được hiển thị ở dạng thập phân thông thường (ví dụ: 0.001 thay vì 1.000e-03).

```python
import numpy as np

np.set_printoptions(precision=3, suppress=True)
array = np.array([0.00012345, 123.456789, 0.9999])
print(array)
```

Kết quả sẽ là:
```python
[ 0.     123.457   1.    ]
```

Trong ví dụ trên:

- Các số thập phân được làm tròn đến 3 chữ số thập phân.
- Các giá trị nhỏ như 0.00012345 hiển thị dưới dạng 0. thay vì 1.234e-04.


In [2]:
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

abalone_train.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.435     0.335   0.110         0.334          0.1355          0.0775   
1   0.585     0.450   0.125         0.874          0.3545          0.2075   
2   0.655     0.510   0.160         1.092          0.3960          0.2825   
3   0.545     0.425   0.125         0.768          0.2940          0.1495   
4   0.545     0.420   0.130         0.879          0.3740          0.1695   

   Shell weight  Age  
0        0.0965    7  
1        0.2250    6  
2        0.3700   14  
3        0.2600   16  
4        0.2300   13

In [3]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop("Age")

In [4]:
abalone_features.columns

Index(['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight'],
      dtype='object')

In [5]:
abalone_labels

0        7
1        6
2       14
3       16
4       13
        ..
3315    15
3316    10
3317    11
3318    16
3319    19
Name: Age, Length: 3320, dtype: int64

In [6]:
type(abalone_labels)

pandas.core.series.Series

In [7]:
abalone_features = np.array(abalone_features)

In [8]:
abalone_features

array([[0.435, 0.335, 0.11 , ..., 0.136, 0.077, 0.097],
       [0.585, 0.45 , 0.125, ..., 0.354, 0.207, 0.225],
       [0.655, 0.51 , 0.16 , ..., 0.396, 0.282, 0.37 ],
       ...,
       [0.53 , 0.42 , 0.13 , ..., 0.374, 0.167, 0.249],
       [0.395, 0.315, 0.105, ..., 0.118, 0.091, 0.119],
       [0.45 , 0.355, 0.12 , ..., 0.115, 0.067, 0.16 ]])

In [9]:
abalone_features.shape

(3320, 7)

In [10]:
abalone_test = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_test.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

abalone_test.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.570     0.465   0.180        1.2950          0.3390          0.2225   
1   0.660     0.530   0.185        1.3485          0.4930          0.2450   
2   0.440     0.345   0.120        0.3650          0.1655          0.0830   
3   0.620     0.475   0.160        1.1295          0.4630          0.2685   
4   0.505     0.410   0.135        0.6570          0.2910          0.1330   

   Shell weight  Age  
0         0.440   12  
1         0.490   12  
2         0.110    7  
3         0.330   10  
4         0.195   15

In [11]:
abalone_features_test = abalone_test.copy()
abalone_labels_test = abalone_features_test.pop("Age")

In [12]:
abalone_features_test = np.array(abalone_features_test)

In [13]:
abalone_features_test

array([[0.57 , 0.465, 0.18 , ..., 0.339, 0.223, 0.44 ],
       [0.66 , 0.53 , 0.185, ..., 0.493, 0.245, 0.49 ],
       [0.44 , 0.345, 0.12 , ..., 0.166, 0.083, 0.11 ],
       ...,
       [0.61 , 0.48 , 0.165, ..., 0.421, 0.264, 0.335],
       [0.565, 0.4  , 0.13 , ..., 0.307, 0.167, 0.18 ],
       [0.59 , 0.49 , 0.135, ..., 0.422, 0.225, 0.285]])

In [14]:
abalone_labels_test

0      12
1      12
2       7
3      10
4      15
       ..
845     9
846     8
847    13
848     8
849    11
Name: Age, Length: 850, dtype: int64

In [15]:
abalone_model = keras.models.Sequential([
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1)
])

In [16]:
abalone_model.compile(
    loss=keras.losses.MeanSquaredError(),
    optimizer=keras.optimizers.Adam(),
    metrics=['accuracy']
)

In [17]:
abalone_model.fit(abalone_features, abalone_labels, epochs=10)

Epoch 1/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 1s 745us/step - accuracy: 0.0000e+00 - loss: 96.4602
Epoch 2/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - accuracy: 2.0213e-04 - loss: 35.5010
Epoch 3/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step - accuracy: 3.1593e-04 - loss: 9.5746
Epoch 4/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 6.3478e-04 - loss: 8.2596
Epoch 5/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - accuracy: 3.2419e-04 - loss: 8.3060
Epoch 6/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step - accuracy: 4.1621e-05 - loss: 7.1566
Epoch 7/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - accuracy: 3.2812e-05 - loss: 7.1054
Epoch 8/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 3.1038e-05 - loss: 6.4620
Epoch 9/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - accuracy: 3.1798e-04 - loss: 6.4700
Epoch 10/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - accuracy: 1.3616e-04 - loss: 5.9435


Khi sử dụng `keras.Sequential`, mô hình `abalone_model` có thể tự động xác định kích thước đầu vào dựa trên hình dạng của dữ liệu đầu vào (`abalone_features.shape`).

Trong trường hợp này, khi bạn huấn luyện mô hình với `abalone_features`, Keras sẽ kiểm tra hình dạng của dữ liệu. Nếu `abalone_features` có dạng `(số mẫu, 7)`, Keras hiểu rằng mỗi mẫu dữ liệu đầu vào có **7 đặc trưng** (features).

Điều này được thực hiện nhờ tính năng tự động suy luận hình dạng đầu vào (input shape inference) của Keras. Khi bạn không chỉ rõ `input_shape` cho lớp đầu tiên của mô hình, Keras sẽ nhận diện hình dạng đầu vào từ lô dữ liệu đầu tiên khi mô hình huấn luyện hoặc dự đoán, giúp xác định rằng mỗi mẫu có 7 đặc trưng.

### Cách thức hoạt động
- Khi bạn gọi `model.fit(...)` hoặc `model.predict(...)` lần đầu tiên, Keras sẽ xác định rằng `abalone_features` có hình dạng `(batch_size, 7)`.
- Keras hiểu rằng lớp `Dense(64)` sẽ nhận đầu vào với kích thước 7 (tương ứng với số đặc trưng), và tự động cấu hình mô hình để nhận đúng số đầu vào này.

### Nếu muốn chỉ định rõ ràng
Bạn cũng có thể chỉ rõ kích thước đầu vào bằng cách cung cấp `input_shape=(7,)` cho lớp đầu tiên, như sau:

```python
abalone_model = keras.models.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(7,)),
    keras.layers.Dense(1)
])
```

Cách này giúp đảm bảo rằng mô hình luôn yêu cầu đầu vào với 7 đặc trưng ngay từ đầu.

`input_shape=(7,)` là một tham số chỉ rõ kích thước đầu vào của dữ liệu cho lớp đầu tiên của mô hình trong Keras. Cụ thể:

- `input_shape=(7,)` có nghĩa là mỗi mẫu đầu vào có **7 đặc trưng (features)**. Dấu phẩy sau số 7 (`(7,)`) cho biết rằng đây là một tuple một chiều (7,) - tức là một vector với 7 giá trị. Đây là dạng thường gặp khi đầu vào là dữ liệu tabular hoặc các mẫu vector trong machine learning.

### Ý nghĩa của `input_shape=(7,)`
- Nó giúp lớp đầu tiên của mô hình Keras biết rằng mỗi mẫu đầu vào sẽ có đúng 7 đặc trưng. Điều này rất quan trọng để đảm bảo rằng các phép tính toán trên lớp đầu tiên sẽ khớp với hình dạng của dữ liệu.
- Nếu `input_shape` không được chỉ định, Keras sẽ đợi dữ liệu thực tế được đưa vào mô hình để tự suy ra hình dạng của đầu vào.

### Giá trị khác cho `input_shape`
`input_shape` có thể nhận nhiều giá trị khác nhau tùy vào loại dữ liệu:

1. **Vector (1D)**: `(n,)`, như `(7,)`, chỉ ra rằng dữ liệu là một vector n phần tử.
2. **Ma trận (2D)**: `(height, width)`, như `(28, 28)` cho ảnh grayscale kích thước 28x28.
3. **Tensor (3D)**: `(height, width, channels)`, như `(32, 32, 3)` cho ảnh màu 32x32 với 3 kênh (RGB).
4. **Tensor nhiều chiều hơn**: Với dữ liệu phức tạp hơn, bạn có thể có `input_shape` với nhiều hơn 3 chiều, chẳng hạn `(time_steps, height, width, channels)` cho dữ liệu video (với các ảnh liên tục theo thời gian).

Ví dụ:
- **Ảnh grayscale 28x28**: `input_shape=(28, 28, 1)`
- **Ảnh màu RGB 32x32**: `input_shape=(32, 32, 3)`
- **Chuỗi thời gian 10 bước, mỗi bước có 3 đặc trưng**: `input_shape=(10, 3)`

### Ví dụ sử dụng
```python
model = keras.models.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(7,)),  # Đầu vào là vector 7 phần tử
    keras.layers.Dense(1)
])
```

Trong ví dụ này, `input_shape=(7,)` chỉ ra rằng mỗi mẫu có 7 đặc trưng, phù hợp cho các bài toán hồi quy hay phân loại với đầu vào vector.

Nếu sau đó chúng ta chuyền vào model một input với shape là (1, 8) (tức có 1 data point và data point có 8 feature) thì sẽ gây ra lỗi
```python
input = np.array([[0.435, 0.335, 0.11 , 0.334, 0.136, 0.077, 6, 6]])
abalone_model.predict(input)
```

Lỗi là:
```python
Input 0 of layer "dense_6" is incompatible with the layer: expected axis -1 of input shape to have value 7, but received input with shape (1, 8)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(1, 8), dtype=float32)
  • training=False
  • mask=None
```

In [18]:
test_loss, test_accuracy = abalone_model.evaluate(abalone_features_test, abalone_labels_test, verbose=2)

27/27 - 0s - 3ms/step - accuracy: 0.0000e+00 - loss: 6.7513


In [19]:
test_loss

6.751287460327148

In [20]:
test_accuracy

0.0

In [21]:
normalize = keras.layers.Normalization()

In [22]:
normalize.adapt(abalone_features)

`normalize = layers.Normalization()` là một lớp (layer) normalization trong Keras, dùng để chuẩn hóa dữ liệu đầu vào của mô hình. Lớp này nằm trong `tf.keras.layers` và có nhiệm vụ chuẩn hóa dữ liệu sao cho mỗi đặc trưng có **trung bình bằng 0** và **độ lệch chuẩn bằng 1**. Chuẩn hóa giúp các giá trị dữ liệu nằm trong khoảng nhỏ hơn, giúp mô hình hội tụ nhanh hơn và ổn định hơn trong quá trình huấn luyện.

### Cách hoạt động của `layers.Normalization`
- Khi sử dụng lớp này, bạn cần **tính toán trước** trung bình và độ lệch chuẩn của dữ liệu huấn luyện, sau đó áp dụng chuẩn hóa cho từng đặc trưng (feature).
- Sau khi được `adapt()` với dữ liệu huấn luyện, lớp này sẽ chuẩn hóa các giá trị đầu vào dựa trên các giá trị trung bình và độ lệch chuẩn đã tính.

### Các bước để sử dụng
1. **Khởi tạo lớp**: `normalize = layers.Normalization()`
2. **Cập nhật thống kê** bằng cách gọi `normalize.adapt(data)`, trong đó `data` là dữ liệu mẫu.
3. **Thêm vào mô hình**: Lớp này sẽ được đặt ở đầu mô hình để chuẩn hóa dữ liệu ngay trước khi vào lớp đầu tiên.

### Ví dụ
```python
from tensorflow.keras import layers

# Khởi tạo lớp Normalization
normalize = layers.Normalization()

# Tính toán trung bình và độ lệch chuẩn của dữ liệu huấn luyện
normalize.adapt(training_data)

# Xây dựng mô hình với lớp chuẩn hóa
model = keras.models.Sequential([
    normalize,  # Áp dụng chuẩn hóa đầu vào
    layers.Dense(64, activation='relu'),
    layers.Dense(1)
])
```

### Các tham số của `layers.Normalization`
Khi khởi tạo `Normalization`, có một số tham số tùy chọn:
- `mean`: Giá trị trung bình tùy chỉnh để chuẩn hóa, nếu không lớp sẽ tự động tính từ dữ liệu.
- `variance`: Độ lệch chuẩn tùy chỉnh để chuẩn hóa.

Khi không cung cấp `mean` và `variance`, lớp sẽ tự động tính các giá trị này bằng cách gọi `adapt()`.

Lớp `Normalization` sẽ chuẩn hóa dữ liệu đầu vào bằng cách áp dụng công thức:

\[
\text{normalized\_value} = \frac{\text{value} - \text{mean}}{\sqrt{\text{variance}}}
\]

Trong đó:
- `mean` là giá trị trung bình của dữ liệu huấn luyện.
- `variance` là phương sai của dữ liệu huấn luyện.

Đây là cách mà dữ liệu đầu vào sẽ được chuyển đổi để có trung bình bằng 0 và độ lệch chuẩn bằng 1.

### Ví dụ minh họa

Giả sử bạn có một mảng dữ liệu đầu vào như sau:

```python
import numpy as np
from tensorflow.keras import layers

# Dữ liệu giả lập
data = np.array([[10, 20, 30],
                 [20, 30, 40],
                 [30, 40, 50]], dtype="float32")

# Khởi tạo lớp Normalization và tính mean và variance
normalize = layers.Normalization()
normalize.adapt(data)
```

Lúc này, lớp `Normalization` sẽ tự động tính:
- `mean` là trung bình của mỗi cột (tính trên toàn bộ `data`)
- `variance` là phương sai của mỗi cột (tính trên toàn bộ `data`)

Cụ thể, với `data` trên:
- `mean` sẽ là `[20, 30, 40]`
- `variance` sẽ là `[66.67, 66.67, 66.67]` (giả sử phương sai là ước lượng gần đúng)

Sau đó, bạn có thể chuẩn hóa dữ liệu bằng cách áp dụng lớp `normalize`:

```python
# Áp dụng lớp normalize
normalized_data = normalize(data)
print(normalized_data)
```

Kết quả sẽ là một mảng mới, với các giá trị đã chuẩn hóa:

```python
<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.2247449, -1.2247449, -1.2247449],
       [ 0.       ,  0.       ,  0.       ],
       [ 1.2247449,  1.2247449,  1.2247449]], dtype=float32)>
```

Giải thích:
- Ở hàng đầu tiên, các giá trị được chuẩn hóa thành -1.2247 (tức là thấp hơn `mean` một độ lệch chuẩn).
- Ở hàng thứ hai, các giá trị là 0 (trung bình của cột).
- Ở hàng cuối cùng, các giá trị là +1.2247 (cao hơn `mean` một độ lệch chuẩn).

Kết quả này cho thấy dữ liệu đã được chuẩn hóa, giúp các lớp tiếp theo trong mô hình hoạt động hiệu quả hơn khi huấn luyện.

Chuẩn hóa dữ liệu thành trung bình 0 và độ lệch chuẩn 1 giúp làm cho dữ liệu đồng nhất về mặt tỷ lệ giữa các đặc trưng, mang lại lợi ích quan trọng trong việc huấn luyện mô hình:

1. **Hội tụ nhanh hơn**: Các đặc trưng có giá trị nằm trong phạm vi nhỏ hơn giúp quá trình tối ưu hóa (như trong thuật toán gradient descent) hội tụ nhanh hơn. Nếu các đặc trưng có phạm vi giá trị khác nhau lớn, thì việc tìm đường đi đến điểm tối ưu sẽ khó khăn hơn vì mô hình có thể nhảy quá mức cần thiết theo chiều có giá trị lớn, và ít thay đổi theo chiều có giá trị nhỏ.

2. **Tránh hiện tượng gradient biến thiên không đều**: Chuẩn hóa giảm thiểu sự khác biệt về tỷ lệ của các gradient, giúp thuật toán học cập nhật các tham số đồng đều hơn. Điều này giúp mô hình huấn luyện ổn định, tránh hiện tượng quá trình học không hiệu quả do gradient của một số đặc trưng quá lớn hoặc quá nhỏ.

3. **Tránh bị chi phối bởi đặc trưng có giá trị lớn**: Khi các đặc trưng nằm trong cùng khoảng giá trị (khoảng từ -1 đến 1 hoặc tương tự), các đặc trưng có tầm quan trọng tương đối với nhau, không có đặc trưng nào chiếm ưu thế chỉ vì phạm vi giá trị của nó lớn hơn những đặc trưng khác.

### Ví dụ minh họa
Nếu dữ liệu có một đặc trưng trong khoảng `[0, 1000]` và đặc trưng khác trong khoảng `[0, 1]`, đặc trưng có giá trị lớn hơn sẽ chi phối quá trình huấn luyện. Khi cả hai đặc trưng được chuẩn hóa, chúng sẽ có tầm quan trọng ngang nhau trong việc tính toán trọng số của mô hình, giúp tối ưu hóa một cách công bằng và hiệu quả.

In [23]:
abalone_features_normalized = normalize(abalone_features)

In [25]:
normalize.mean

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=array([[0.523, 0.407, 0.139, 0.825, 0.358, 0.18 , 0.238]], dtype=float32)>

In [24]:
abalone_features_normalized

<tf.Tensor: shape=(3320, 7), dtype=float32, numpy=
array([[-0.724, -0.715, -0.685, ..., -1.   , -0.932, -1.008],
       [ 0.514,  0.434, -0.334, ..., -0.014,  0.248, -0.092],
       [ 1.092,  1.033,  0.485, ...,  0.172,  0.929,  0.942],
       ...,
       [ 0.06 ,  0.134, -0.217, ...,  0.076, -0.119,  0.079],
       [-1.054, -0.915, -0.803, ..., -1.077, -0.809, -0.844],
       [-0.6  , -0.515, -0.451, ..., -1.095, -1.032, -0.556]],
      dtype=float32)>

In [30]:
norm_abalone_model = keras.models.Sequential([
    normalize,
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1)
])

In [33]:
norm_abalone_model.compile(
    loss=keras.losses.MeanSquaredError(),
    optimizer=keras.optimizers.Adam(),
    metrics=['accuracy']
)

In [34]:
norm_abalone_model.fit(abalone_features, abalone_labels, epochs=100)

Epoch 1/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 1s 777us/step - accuracy: 2.3753e-04 - loss: 12.3605
Epoch 2/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 6.5958e-04 - loss: 9.5252
Epoch 3/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - accuracy: 0.0015 - loss: 5.2651
Epoch 4/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 1.5946e-04 - loss: 4.7156
Epoch 5/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 1.3739e-04 - loss: 4.8409
Epoch 6/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.0013 - loss: 4.1258
Epoch 7/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - accuracy: 2.6371e-04 - loss: 4.5573
Epoch 8/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 9.3831e-04 - loss: 4.3974
Epoch 9/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 718us/step - accuracy: 6.8664e-04 - loss: 4.0650
Epoch 10/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 1.7031e-04 - loss: 4.4124
Epoch 11/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - accuracy: 9.3912e-

In [35]:
test_loss, test_accuracy = abalone_model.evaluate(abalone_features_test, abalone_labels_test, verbose=2)

27/27 - 0s - 985us/step - accuracy: 0.0000e+00 - loss: 6.7513


In [36]:
test_loss

6.751287460327148

In [37]:
test_accuracy

0.0

In [38]:
model = keras.models.Sequential([
    layers.Input(shape=(7,)),  # Đầu vào với 7 đặc trưng
    normalize,
    layers.Dense(64, activation='relu'),  # Lớp ẩn đầu tiên với 64 nơ-ron
    layers.Dense(32, activation='relu'),  # Lớp ẩn thứ hai với 32 nơ-ron
    layers.Dense(1)  # Lớp đầu ra cho giá trị tuổi (regression)
])

# Biên dịch mô hình
model.compile(optimizer='adam',
              loss='mean_squared_error',  # Sử dụng MSE cho bài toán hồi quy
              metrics=['accuracy'])  # Mean Absolute Error để đánh giá mô hình

# Huấn luyện mô hình
model.fit(abalone_features, abalone_labels, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 1.0634e-04 - loss: 86.8551 - val_accuracy: 0.0000e+00 - val_loss: 29.9429
Epoch 2/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 7.7572e-04 - loss: 27.6563 - val_accuracy: 0.0000e+00 - val_loss: 13.4768
Epoch 3/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 3.5551e-04 - loss: 12.9791 - val_accuracy: 0.0000e+00 - val_loss: 6.7564
Epoch 4/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 1.3501e-05 - loss: 7.3426 - val_accuracy: 0.0000e+00 - val_loss: 6.1900
Epoch 5/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 5.1937e-05 - loss: 6.5209 - val_accuracy: 0.0000e+00 - val_loss: 5.8137
Epoch 6/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 3.3330e-04 - loss: 6.9335 - val_accuracy: 0.0000e+00 - val_loss: 5.6219
Epoch 7/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 7.9402e-04 - loss: 5.5207 - val_accuracy: 0.0000e+00 - val_loss: 5.4318
Epoch 8/100
83/83 ━━━━━━━━━━━━━━━━━━━━ 0

In [39]:
test_loss, test_accuracy = model.evaluate(abalone_features_test, abalone_labels_test, verbose=2)

27/27 - 0s - 1ms/step - accuracy: 0.0000e+00 - loss: 5.1988
