In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6],
])
b = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12],
])

In [3]:
result_1 = tf.stack([a, b], 1)

In [4]:
result_0 = tf.stack([a, b], 0)

In [5]:
result_0

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])>

In [6]:
result_1

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 7,  8]],

       [[ 3,  4],
        [ 9, 10]],

       [[ 5,  6],
        [11, 12]]])>

In [7]:
result_0[:,:,0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  3,  5],
       [ 7,  9, 11]])>

In [8]:
a = tf.constant([4])
b = tf.constant([5])

In [9]:
result = tf.stack([a, b], 1)

In [10]:
result.numpy().shape

(1, 2)

In [11]:
x = tf.constant([
    [1, 2],
    [3, 4]
])

In [12]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [13]:
x.numpy()

array([[1, 2],
       [3, 4]])