In [1]:
import tensorflow as tf

# Ví dụ tensor inputs với shape (batch_size, timestep, 4)
batch_size, timestep, feature = 2, 3, 4
inputs = tf.random.uniform((batch_size, timestep, feature))


In [3]:
inputs

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.05347204, 0.23174131, 0.356853  , 0.01264489],
        [0.8748212 , 0.9204689 , 0.20400429, 0.55215275],
        [0.13530612, 0.96285844, 0.2902509 , 0.974977  ]],

       [[0.03828859, 0.55735946, 0.98155844, 0.02991629],
        [0.73911345, 0.3835374 , 0.30400229, 0.03143156],
        [0.25717103, 0.2473135 , 0.45186186, 0.15905678]]], dtype=float32)>

In [4]:
# Chọn các giá trị ở index 1 và 2 của mỗi timestep trong feature
selected_features = inputs[:, :, 1:3]  # Shape: (batch_size, timestep, 2)

# Tìm giá trị max và min ở cặp (1, 2)
max_vals = tf.reduce_max(selected_features, axis=-1, keepdims=True)  # Shape: (batch_size, timestep, 1)
min_vals = tf.reduce_min(selected_features, axis=-1, keepdims=True)  # Shape: (batch_size, timestep, 1)

# Kết hợp max và min thành tensor mới có max tại index 1 và min tại index 2
swapped_features = tf.concat([max_vals, min_vals], axis=-1)  # Shape: (batch_size, timestep, 2)

# Ghép các feature lại với nhau, thay thế các giá trị ở index 1 và 2 bằng tensor đã hoán đổi
outputs = tf.concat([inputs[:, :, :1], swapped_features, inputs[:, :, 3:]], axis=-1)

print("Original Tensor:\n", inputs)
print("\nSwapped Tensor:\n", outputs)


Original Tensor:
 tf.Tensor(
[[[0.05347204 0.23174131 0.356853   0.01264489]
  [0.8748212  0.9204689  0.20400429 0.55215275]
  [0.13530612 0.96285844 0.2902509  0.974977  ]]

 [[0.03828859 0.55735946 0.98155844 0.02991629]
  [0.73911345 0.3835374  0.30400229 0.03143156]
  [0.25717103 0.2473135  0.45186186 0.15905678]]], shape=(2, 3, 4), dtype=float32)

Swapped Tensor:
 tf.Tensor(
[[[0.05347204 0.356853   0.23174131 0.01264489]
  [0.8748212  0.9204689  0.20400429 0.55215275]
  [0.13530612 0.96285844 0.2902509  0.974977  ]]

 [[0.03828859 0.98155844 0.55735946 0.02991629]
  [0.73911345 0.3835374  0.30400229 0.03143156]
  [0.25717103 0.45186186 0.2473135  0.15905678]]], shape=(2, 3, 4), dtype=float32)


In [5]:
import numpy as np

In [16]:
inputs = np.random.randint(0, 3, size=(2, 3, 4))
inputs_1_2 = tf.gather(inputs, [1, 2], axis=-1)
tf.reduce_min(inputs_1_2,  axis=-1, keepdims=True)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [1],
        [0]],

       [[0],
        [0],
        [0]]])>

In [17]:
inputs

array([[[1, 2, 1, 0],
        [2, 2, 1, 1],
        [0, 0, 2, 0]],

       [[0, 1, 0, 1],
        [0, 0, 0, 0],
        [2, 1, 0, 0]]])