In [1]:
import numpy as np

In [2]:
np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4]
]).shape

(2, 4)

In [3]:
a = np.array([
    [[2, 3], [2, 3], [2, 3], [2, 3]],
    [[2, 3], [2, 3], [2, 3], [2, 3]]
])

In [4]:
b = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [5]:
b.shape

(2, 2, 3)

In [8]:
b_1 = b.dot(np.array([[10, 10, 10], [10, 10, 10], [10, 10, 10]]))

In [9]:
b_1

array([[[ 60,  60,  60],
        [150, 150, 150]],

       [[240, 240, 240],
        [330, 330, 330]]])

In [10]:
b_1.shape

(2, 2, 3)

In [11]:
b.dot(np.array([10, 10, 10]).reshape(3,1))

array([[[ 60],
        [150]],

       [[240],
        [330]]])

In [12]:
b.dot(np.array([10, 10, 10]))

array([[ 60, 150],
       [240, 330]])

In [13]:
b.dot(np.array([10, 10, 10]).reshape(1, 3))

ValueError: shapes (2,2,3) and (1,3) not aligned: 3 (dim 2) != 1 (dim 0)